import modules.color as Color

CAPTION = Color.CYAN,
LABEL = Color.RED,
BUTTON = Color.RED, Color.GREEN, Color.BLUE
BUTTON_LESSER = Color.GREY, Color.RED, Color.CYAN
# NORM, HOVER, CLICK, WAIT, LOCK, GHOST
SPECIAL = Color.OTHER.RED, Color.OTHER.ORANGE, Color.OTHER.YELLOW, Color.OTHER.GREEN, Color.OTHER.BLUE, Color.OTHER.PURPLE
#SPECIAL = Color.GREY, Color.RED, Color.CYAN, Color.BLACK, Color.NEON_GREEN, Color.GREEN
TOGGLE = Color.ORANGE, Color.BLACK, Color.YELLOW, Color.GREEN
TICKER = Color.OTHER.RED,  Color.RED,  Color.ORANGE, Color.GREY 